services:
  - type: web
    name: ticketing-system
    env: node
    plan: free
    
    buildCommand: npm install && npm run build
    startCommand: npm start
    
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: JWT_SECRET
        scope: build,runtime
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://ticketing-system.onrender.com
